### ISSUE TITLE
Request: add first image from feed item

### ISSUE THREAD

**Issue by jeroenpraat** [thomasb22/feedMastodon#4]
It would be great if it was possible that feedMastodon could scrape the first image from a feed item and post it to Mastodon.

To make sure unusable images are not scraped, a min. limit of 50KB would be reasonable. 1 MB would be a good max. limit.

**Comment by jeroenpraat** [comment]
@thomasb22 I had an error this morning because of en epub file as a enclosure in the feed item.

It gave this error:

```py
Traceback (most recent call last):
  File "feedMastodon.py", line 138, in <module>
    pictures_ids.append( mastodon.media_post(tmppath) )
  File "/usr/local/lib/python3.5/dist-packages/mastodon/Mastodon.py", line 811, in media_post
    raise MastodonIllegalArgumentError('Could not determine mime type'
mastodon.Mastodon.MastodonIllegalArgumentError: Could not determine mime type or data passed directly without mime type.
```

Cause the pyhton script crashed, the .epub file remained in the tmp directory. Since then I had the following error, although the script worked for other (new) items.

```py
Traceback (most recent call last):
  File "feedMastodon.py", line 154, in <module>
    os.rmdir(tmpdir)
OSError: [Errno 39] Directory not empty: 'tmp'
```

Removing the tmp directory fixed it, until the feed item with the epub was parsed again. Changing show_picture to False fixed it for now.
